// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package account

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-twentysix/sdk/go/twentysix/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type TwentySixAccount struct {
	pulumi.CustomResourceState

	Address        pulumi.StringOutput    `pulumi:"address"`
	DerivationPath pulumi.StringPtrOutput `pulumi:"derivationPath"`
	Mnemonic       pulumi.StringPtrOutput `pulumi:"mnemonic"`
	PrivateKey     pulumi.StringPtrOutput `pulumi:"privateKey"`
	PublicKey      pulumi.StringOutput    `pulumi:"publicKey"`
}

// NewTwentySixAccount registers a new resource with the given unique name, arguments, and options.
func NewTwentySixAccount(ctx *pulumi.Context,
	name string, args *TwentySixAccountArgs, opts ...pulumi.ResourceOption) (*TwentySixAccount, error) {
	if args == nil {
		args = &TwentySixAccountArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource TwentySixAccount
	err := ctx.RegisterResource("twentysix:account:TwentySixAccount", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetTwentySixAccount gets an existing TwentySixAccount resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetTwentySixAccount(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *TwentySixAccountState, opts ...pulumi.ResourceOption) (*TwentySixAccount, error) {
	var resource TwentySixAccount
	err := ctx.ReadResource("twentysix:account:TwentySixAccount", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering TwentySixAccount resources.
type twentySixAccountState struct {
}

type TwentySixAccountState struct {
}

func (TwentySixAccountState) ElementType() reflect.Type {
	return reflect.TypeOf((*twentySixAccountState)(nil)).Elem()
}

type twentySixAccountArgs struct {
	DerivationPath *string `pulumi:"derivationPath"`
	Mnemonic       *string `pulumi:"mnemonic"`
	PrivateKey     *string `pulumi:"privateKey"`
}

// The set of arguments for constructing a TwentySixAccount resource.
type TwentySixAccountArgs struct {
	DerivationPath pulumi.StringPtrInput
	Mnemonic       pulumi.StringPtrInput
	PrivateKey     pulumi.StringPtrInput
}

func (TwentySixAccountArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*twentySixAccountArgs)(nil)).Elem()
}

type TwentySixAccountInput interface {
	pulumi.Input

	ToTwentySixAccountOutput() TwentySixAccountOutput
	ToTwentySixAccountOutputWithContext(ctx context.Context) TwentySixAccountOutput
}

func (*TwentySixAccount) ElementType() reflect.Type {
	return reflect.TypeOf((**TwentySixAccount)(nil)).Elem()
}

func (i *TwentySixAccount) ToTwentySixAccountOutput() TwentySixAccountOutput {
	return i.ToTwentySixAccountOutputWithContext(context.Background())
}

func (i *TwentySixAccount) ToTwentySixAccountOutputWithContext(ctx context.Context) TwentySixAccountOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TwentySixAccountOutput)
}

type TwentySixAccountOutput struct{ *pulumi.OutputState }

func (TwentySixAccountOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**TwentySixAccount)(nil)).Elem()
}

func (o TwentySixAccountOutput) ToTwentySixAccountOutput() TwentySixAccountOutput {
	return o
}

func (o TwentySixAccountOutput) ToTwentySixAccountOutputWithContext(ctx context.Context) TwentySixAccountOutput {
	return o
}

func (o TwentySixAccountOutput) Address() pulumi.StringOutput {
	return o.ApplyT(func(v *TwentySixAccount) pulumi.StringOutput { return v.Address }).(pulumi.StringOutput)
}

func (o TwentySixAccountOutput) DerivationPath() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *TwentySixAccount) pulumi.StringPtrOutput { return v.DerivationPath }).(pulumi.StringPtrOutput)
}

func (o TwentySixAccountOutput) Mnemonic() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *TwentySixAccount) pulumi.StringPtrOutput { return v.Mnemonic }).(pulumi.StringPtrOutput)
}

func (o TwentySixAccountOutput) PrivateKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *TwentySixAccount) pulumi.StringPtrOutput { return v.PrivateKey }).(pulumi.StringPtrOutput)
}

func (o TwentySixAccountOutput) PublicKey() pulumi.StringOutput {
	return o.ApplyT(func(v *TwentySixAccount) pulumi.StringOutput { return v.PublicKey }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*TwentySixAccountInput)(nil)).Elem(), &TwentySixAccount{})
	pulumi.RegisterOutputType(TwentySixAccountOutput{})
}
