// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Twentysix.Account
{
    [TwentysixResourceType("twentysix:account:TwentySixAccount")]
    public partial class TwentySixAccount : global::Pulumi.CustomResource
    {
        [Output("address")]
        public Output<string> Address { get; private set; } = null!;

        [Output("derivationPath")]
        public Output<string?> DerivationPath { get; private set; } = null!;

        [Output("mnemonic")]
        public Output<string?> Mnemonic { get; private set; } = null!;

        [Output("privateKey")]
        public Output<string?> PrivateKey { get; private set; } = null!;

        [Output("publicKey")]
        public Output<string> PublicKey { get; private set; } = null!;


        /// <summary>
        /// Create a TwentySixAccount resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public TwentySixAccount(string name, TwentySixAccountArgs? args = null, CustomResourceOptions? options = null)
            : base("twentysix:account:TwentySixAccount", name, args ?? new TwentySixAccountArgs(), MakeResourceOptions(options, ""))
        {
        }

        private TwentySixAccount(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("twentysix:account:TwentySixAccount", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing TwentySixAccount resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static TwentySixAccount Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new TwentySixAccount(name, id, options);
        }
    }

    public sealed class TwentySixAccountArgs : global::Pulumi.ResourceArgs
    {
        [Input("derivationPath")]
        public Input<string>? DerivationPath { get; set; }

        [Input("mnemonic")]
        public Input<string>? Mnemonic { get; set; }

        [Input("privateKey")]
        public Input<string>? PrivateKey { get; set; }

        public TwentySixAccountArgs()
        {
        }
        public static new TwentySixAccountArgs Empty => new TwentySixAccountArgs();
    }
}
