# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_twentysix.account as __account
    account = __account
    import pulumi_twentysix.volume as __volume
    volume = __volume
else:
    account = _utilities.lazy_import('pulumi_twentysix.account')
    volume = _utilities.lazy_import('pulumi_twentysix.volume')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "twentysix",
  "mod": "account",
  "fqn": "pulumi_twentysix.account",
  "classes": {
   "twentysix:account:TwentySixAccount": "TwentySixAccount"
  }
 },
 {
  "pkg": "twentysix",
  "mod": "volume",
  "fqn": "pulumi_twentysix.volume",
  "classes": {
   "twentysix:volume:TwentySixVolume": "TwentySixVolume"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "twentysix",
  "token": "pulumi:providers:twentysix",
  "fqn": "pulumi_twentysix",
  "class": "Provider"
 }
]
"""
)
