// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { TwentySixVolumeArgs } from "./twentySixVolume";
export type TwentySixVolume = import("./twentySixVolume").TwentySixVolume;
export const TwentySixVolume: typeof import("./twentySixVolume").TwentySixVolume = null as any;
utilities.lazyLoad(exports, ["TwentySixVolume"], () => require("./twentySixVolume"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "twentysix:volume:TwentySixVolume":
                return new TwentySixVolume(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("twentysix", "volume", _module)
