// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.twentysix.volume;




public final class TwentySixVolumeArgs extends com.pulumi.resources.ResourceArgs {

    public static final TwentySixVolumeArgs Empty = new TwentySixVolumeArgs();

    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private TwentySixVolumeArgs $;

        public Builder() {
            $ = new TwentySixVolumeArgs();
        }
        public TwentySixVolumeArgs build() {
            return $;
        }
    }

}
