// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.twentysix.volume;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.twentysix.Utilities;
import com.pulumi.twentysix.volume.TwentySixVolumeArgs;
import java.lang.String;
import javax.annotation.Nullable;

@ResourceType(type="twentysix:volume:TwentySixVolume")
public class TwentySixVolume extends com.pulumi.resources.CustomResource {
    @Export(name="ipfsHash", refs={String.class}, tree="[0]")
    private Output<String> ipfsHash;

    public Output<String> ipfsHash() {
        return this.ipfsHash;
    }
    @Export(name="messageHash", refs={String.class}, tree="[0]")
    private Output<String> messageHash;

    public Output<String> messageHash() {
        return this.messageHash;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public TwentySixVolume(String name) {
        this(name, TwentySixVolumeArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public TwentySixVolume(String name, @Nullable TwentySixVolumeArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public TwentySixVolume(String name, @Nullable TwentySixVolumeArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("twentysix:volume:TwentySixVolume", name, args == null ? TwentySixVolumeArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private TwentySixVolume(String name, Output<String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("twentysix:volume:TwentySixVolume", name, null, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static TwentySixVolume get(String name, Output<String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new TwentySixVolume(name, id, options);
    }
}
