// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.twentysix.account;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.twentysix.Utilities;
import com.pulumi.twentysix.account.TwentySixAccountArgs;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="twentysix:account:TwentySixAccount")
public class TwentySixAccount extends com.pulumi.resources.CustomResource {
    @Export(name="address", refs={String.class}, tree="[0]")
    private Output<String> address;

    public Output<String> address() {
        return this.address;
    }
    @Export(name="derivationPath", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> derivationPath;

    public Output<Optional<String>> derivationPath() {
        return Codegen.optional(this.derivationPath);
    }
    @Export(name="mnemonic", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> mnemonic;

    public Output<Optional<String>> mnemonic() {
        return Codegen.optional(this.mnemonic);
    }
    @Export(name="privateKey", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> privateKey;

    public Output<Optional<String>> privateKey() {
        return Codegen.optional(this.privateKey);
    }
    @Export(name="publicKey", refs={String.class}, tree="[0]")
    private Output<String> publicKey;

    public Output<String> publicKey() {
        return this.publicKey;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public TwentySixAccount(String name) {
        this(name, TwentySixAccountArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public TwentySixAccount(String name, @Nullable TwentySixAccountArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public TwentySixAccount(String name, @Nullable TwentySixAccountArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("twentysix:account:TwentySixAccount", name, args == null ? TwentySixAccountArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private TwentySixAccount(String name, Output<String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("twentysix:account:TwentySixAccount", name, null, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static TwentySixAccount get(String name, Output<String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new TwentySixAccount(name, id, options);
    }
}
