// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.twentysix.account;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class TwentySixAccountArgs extends com.pulumi.resources.ResourceArgs {

    public static final TwentySixAccountArgs Empty = new TwentySixAccountArgs();

    @Import(name="derivationPath")
    private @Nullable Output<String> derivationPath;

    public Optional<Output<String>> derivationPath() {
        return Optional.ofNullable(this.derivationPath);
    }

    @Import(name="mnemonic")
    private @Nullable Output<String> mnemonic;

    public Optional<Output<String>> mnemonic() {
        return Optional.ofNullable(this.mnemonic);
    }

    @Import(name="privateKey")
    private @Nullable Output<String> privateKey;

    public Optional<Output<String>> privateKey() {
        return Optional.ofNullable(this.privateKey);
    }

    private TwentySixAccountArgs() {}

    private TwentySixAccountArgs(TwentySixAccountArgs $) {
        this.derivationPath = $.derivationPath;
        this.mnemonic = $.mnemonic;
        this.privateKey = $.privateKey;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(TwentySixAccountArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private TwentySixAccountArgs $;

        public Builder() {
            $ = new TwentySixAccountArgs();
        }

        public Builder(TwentySixAccountArgs defaults) {
            $ = new TwentySixAccountArgs(Objects.requireNonNull(defaults));
        }

        public Builder derivationPath(@Nullable Output<String> derivationPath) {
            $.derivationPath = derivationPath;
            return this;
        }

        public Builder derivationPath(String derivationPath) {
            return derivationPath(Output.of(derivationPath));
        }

        public Builder mnemonic(@Nullable Output<String> mnemonic) {
            $.mnemonic = mnemonic;
            return this;
        }

        public Builder mnemonic(String mnemonic) {
            return mnemonic(Output.of(mnemonic));
        }

        public Builder privateKey(@Nullable Output<String> privateKey) {
            $.privateKey = privateKey;
            return this;
        }

        public Builder privateKey(String privateKey) {
            return privateKey(Output.of(privateKey));
        }

        public TwentySixAccountArgs build() {
            return $;
        }
    }

}
