# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

__all__ = ['TwentySixVolumeArgs', 'TwentySixVolume']

@pulumi.input_type
class TwentySixVolumeArgs:
    def __init__(__self__):
        """
        The set of arguments for constructing a TwentySixVolume resource.
        """
        pass


class TwentySixVolume(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 __props__=None):
        """
        Create a TwentySixVolume resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[TwentySixVolumeArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a TwentySixVolume resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param TwentySixVolumeArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(TwentySixVolumeArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = TwentySixVolumeArgs.__new__(TwentySixVolumeArgs)

            __props__.__dict__["ipfs_hash"] = None
            __props__.__dict__["message_hash"] = None
        super(TwentySixVolume, __self__).__init__(
            'twentysix:volume:TwentySixVolume',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'TwentySixVolume':
        """
        Get an existing TwentySixVolume resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = TwentySixVolumeArgs.__new__(TwentySixVolumeArgs)

        __props__.__dict__["ipfs_hash"] = None
        __props__.__dict__["message_hash"] = None
        return TwentySixVolume(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter(name="ipfsHash")
    def ipfs_hash(self) -> pulumi.Output[str]:
        return pulumi.get(self, "ipfs_hash")

    @property
    @pulumi.getter(name="messageHash")
    def message_hash(self) -> pulumi.Output[str]:
        return pulumi.get(self, "message_hash")

