// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { TwentySixAccountArgs } from "./twentySixAccount";
export type TwentySixAccount = import("./twentySixAccount").TwentySixAccount;
export const TwentySixAccount: typeof import("./twentySixAccount").TwentySixAccount = null as any;
utilities.lazyLoad(exports, ["TwentySixAccount"], () => require("./twentySixAccount"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "twentysix:account:TwentySixAccount":
                return new TwentySixAccount(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("twentysix", "account", _module)
