// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export class TwentySixAccount extends pulumi.CustomResource {
    /**
     * Get an existing TwentySixAccount resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): TwentySixAccount {
        return new TwentySixAccount(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twentysix:account:TwentySixAccount';

    /**
     * Returns true if the given object is an instance of TwentySixAccount.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is TwentySixAccount {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === TwentySixAccount.__pulumiType;
    }

    public /*out*/ readonly address!: pulumi.Output<string>;
    public readonly derivationPath!: pulumi.Output<string | undefined>;
    public readonly mnemonic!: pulumi.Output<string | undefined>;
    public readonly privateKey!: pulumi.Output<string | undefined>;
    public /*out*/ readonly publicKey!: pulumi.Output<string>;

    /**
     * Create a TwentySixAccount resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: TwentySixAccountArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["derivationPath"] = args ? args.derivationPath : undefined;
            resourceInputs["mnemonic"] = args ? args.mnemonic : undefined;
            resourceInputs["privateKey"] = args ? args.privateKey : undefined;
            resourceInputs["address"] = undefined /*out*/;
            resourceInputs["publicKey"] = undefined /*out*/;
        } else {
            resourceInputs["address"] = undefined /*out*/;
            resourceInputs["derivationPath"] = undefined /*out*/;
            resourceInputs["mnemonic"] = undefined /*out*/;
            resourceInputs["privateKey"] = undefined /*out*/;
            resourceInputs["publicKey"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(TwentySixAccount.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a TwentySixAccount resource.
 */
export interface TwentySixAccountArgs {
    derivationPath?: pulumi.Input<string>;
    mnemonic?: pulumi.Input<string>;
    privateKey?: pulumi.Input<string>;
}
